### PR TITLE
More pages that should have `noindex`

### PR DESCRIPTION
**Pull request by IanButterworth**
@mortenpi, it's proven tricky to find a reliable find & replace approach..
I noticed some of these still coming up in google search console

This attempt is using VS code's multi-line find & replace, excluding `./en/v1*, ./en/1*, ./en/latest*`

### CODE REVIEW

**Comment by mortenpi** [comment]
I assumed we were applying it to all pages anyway (from the old docs). So this should now do it?

**Comment by IanButterworth** [comment]
Indeed. These just slipped through given I didn't have my find and replace game down before.. I think it's perfected now

**Comment by fredrikekre** [comment]
So, not sure if this is the PR that caused this, but probably one of your PRs @ianshmean. When searching for `pkg julia docs`, the top result is now https://docs.julialang.org/en/v1.0.0/stdlib/Pkg/ when it used to be https://docs.julialang.org/en/v1/stdlib/Pkg/index.html. We definitely want the `v1` URL.

**Comment by IanButterworth** [comment]
That’s unfortunate. I can’t immediately see why any of the PRs would’ve penalized the v1 version or promoted the v1.0.0 version. 

Also, the canonical url that’s present on the v1.0.0 version that points to the v1 version should be preventing this. 

Frustrating. Are you aware of any issues like this with other queries/pages?

**Comment by ianshmean** [comment]
That’s unfortunate. I can’t immediately see why any of the PRs would’ve penalized the v1 version or promoted the v1.0.0 version. 

Also, the canonical url that’s present on the v1.0.0 version that points to the v1 version should be preventing this. 

Frustrating. Are you aware of any issues like this with other queries/pages?

**Comment by IanButterworth** [comment]
Oddly, Google Search Console thinks that the v1.0.0 version isn't on google, because it's preferring the self-assigned (and google-assigned) canonical.. doing what it should.. I guess the issue is noise in their system

Screen Shot 2019-09-17 at 9 06 26 AM

**Pull request merged**
