### PR TITLE
Manually add `objects.inv` for 1.10.2

### PR DESCRIPTION
**Pull request by goerz**
File was manually generated the same way as in https://github.com/JuliaLang/julia/pull/53597

This is a one-time fix, since subsequent releases of Julia should write the inventory file automatically:

* For Julia 1.10.3: https://github.com/JuliaLang/julia/pull/53597
* For Julia 1.11: backport of https://github.com/JuliaLang/julia/pull/53571, seems to have been done in https://github.com/JuliaLang/julia/pull/53543
* For Julia 1.12: https://github.com/JuliaLang/julia/pull/53571

This PR will make the inventory file available "immediately" to the current online docs. I'm still planning to make an announcement of [DocumenterInterLinks](https://github.com/JuliaDocs/DocumenterInterLinks.jl) soonish, and it would be extra nice if I could say

> Put
>
> ```
> links = InterLinks(
>     "Julia" => "https://docs.julialang.org/en/v1/",
> )
> ```
>
> in your `make.jl` file

instead of

> Download and unzip the `Julia.toml` file from https://github.com/JuliaDocs/DocumenterInterLinks.jl/wiki/Inventory-File-Repository, put it in your `docs/src/inventories` folder, and then add
>
> ```
> links = InterLinks(
>     "Julia" => (
>         "https://docs.julialang.org/en/v1/",
>         "https://docs.julialang.org/en/v1/objects.inv",
>         joinpath(@__DIR__, "src", "inventories", "Julia.toml"),
>     ),
> )
> ```
>
> in your `make.jl` file.

So, I'm hoping you can make an exception to

> Pull Requests will not be accepted to this repository.
> Contributions for the Julia documentation should be made to
> Julia's GitHub repository (https://github.com/JuliaLang/julia).

### CODE REVIEW

**Comment by goerz** [comment]
@mortenpi

**Comment by goerz** [comment]
~~Ugh, hold on, I screwed that up (wrong format: toml, not objects.inv)~~

**Comment by goerz** [comment]
Ok, fixed. Sorry about that.

**Comment by mortenpi** [comment]
Ah, we should have merged this ages ago sorry!

**Pull request merged**
